version: '3.8'

services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: always             # run as a service    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./auth/data:/data
    ports:
      - 8888:8080
    environment:
      DOZZLE_ENABLE_ACTIONS: true      
      DOZZLE_AUTH_PROVIDER: simple
      DOZZLE_NO_ANALYTICS: 1
      
  db:
    container_name: postgres
    image: postgres:16
    restart: always             # run as a service    
    environment:
      POSTGRES_USER: flectra
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
        - ./postgresql:/var/lib/postgresql/data
    
  flectra:
    image: flectrahq/flectra:3.0
    user: flectra
    restart: always             # run as a service 
    ports:
      - 10020:7073
      - 20020:7072 # live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=flectra
      - PASSWORD=password
    volumes:
      # - ./etc/timezone:/etc/timezone:ro
      # - ./etc/localtime:/etc/localtime:ro
      - ./etc/config:/var/lib/flectra:rw
      - ./etc/addons:/mnt/extra-addons:ro
      - ./etc/logs:/var/log/flectra:rw
      # - ./etc/geoip-db:/usr/share/GeoIP:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
    depends_on:
      - db
    
